name: Publish Website to CPanel

on:
  push:
    branches:
      - main

jobs:
  FTP-Deploy-Action:
    name: FTP Deploy Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # ดึงโค้ดจาก repository
      with:
        fetch-depth: 2

    - name: FTP Deploy Action
      uses: appleboy/ftp-action@v1.0.0
      with:
        host: ${{ secrets.FTP_SERVER }}  # ข้อมูลเซิร์ฟเวอร์ FTP
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  # ใช้ FTP ปกติ
        remote-dir: /home/tlgmrvbr/tlgm_api  # โฟลเดอร์ปลายทางบน FTP server
