name : Publish Website to CPanel
on : 
  push : 
    branches : 
      - main 
jobs : 
  FTP-Deploy-Action : 
    name : FTP-Deplot-Action 
    runs-on : ubuntu-latest 
    steps : 
    - uses : action/checkout@v2.1.0
      with : 
        fetch-depth : 2 
    - name : FTP-Deplot-Action 
      uses : SamKrirk/FTP-Deplot-Action@3.1.1
      with : 
        ftp-server : ${{ secrets.FTP_SERVER }}
        ftp-username :  ${{ secrets.FTP_USERNAME }}
        ftp-password :  ${{ secrets.FTP_PASSWORD }}
        ftp-directory: "/home/tlgmrvbr/tlgm_api"
